/**
 * Aisle Classification Utility
 *
 * Classifies ingredients into British supermarket aisle categories.
 * Uses dictionary lookup on normalized ingredient names.
 */

// Define aisle types as a const array for type safety
export const AISLES = [
  "Fresh Produce",
  "Meat & Seafood",
  "Dairy & Eggs",
  "Bakery",
  "Chilled",
  "Frozen",
  "Tinned & Canned",
  "Pasta Rice & Grains",
  "Herbs & Spices",
  "Condiments & Sauces",
  "World Foods",
  "Baking",
  "Drinks",
  "Other",
] as const;

export type Aisle = (typeof AISLES)[number];

// Dictionary mapping normalized ingredient keywords to aisles
const INGREDIENT_TO_AISLE: Record<string, Aisle> = {
  // ─── Fresh Produce ────────────────────────────────────────────────────────
  // Fruits
  apple: "Fresh Produce",
  apricot: "Fresh Produce",
  avocado: "Fresh Produce",
  banana: "Fresh Produce",
  blackberry: "Fresh Produce",
  blueberry: "Fresh Produce",
  cherry: "Fresh Produce",
  clementine: "Fresh Produce",
  coconut: "Fresh Produce",
  cranberry: "Fresh Produce",
  date: "Fresh Produce",
  fig: "Fresh Produce",
  grape: "Fresh Produce",
  grapefruit: "Fresh Produce",
  kiwi: "Fresh Produce",
  lemon: "Fresh Produce",
  lime: "Fresh Produce",
  lychee: "Fresh Produce",
  mango: "Fresh Produce",
  melon: "Fresh Produce",
  nectarine: "Fresh Produce",
  orange: "Fresh Produce",
  papaya: "Fresh Produce",
  passionfruit: "Fresh Produce",
  peach: "Fresh Produce",
  pear: "Fresh Produce",
  pineapple: "Fresh Produce",
  plum: "Fresh Produce",
  pomegranate: "Fresh Produce",
  raspberry: "Fresh Produce",
  rhubarb: "Fresh Produce",
  satsuma: "Fresh Produce",
  strawberry: "Fresh Produce",
  tangerine: "Fresh Produce",
  watermelon: "Fresh Produce",

  // Vegetables
  artichoke: "Fresh Produce",
  asparagus: "Fresh Produce",
  aubergine: "Fresh Produce",
  beetroot: "Fresh Produce",
  "bell pepper": "Fresh Produce",
  broccoli: "Fresh Produce",
  "brussels sprout": "Fresh Produce",
  butternut: "Fresh Produce",
  cabbage: "Fresh Produce",
  carrot: "Fresh Produce",
  cauliflower: "Fresh Produce",
  celeriac: "Fresh Produce",
  celery: "Fresh Produce",
  chard: "Fresh Produce",
  chicory: "Fresh Produce",
  chilli: "Fresh Produce",
  corn: "Fresh Produce",
  courgette: "Fresh Produce",
  cucumber: "Fresh Produce",
  eggplant: "Fresh Produce",
  endive: "Fresh Produce",
  fennel: "Fresh Produce",
  garlic: "Fresh Produce",
  ginger: "Fresh Produce",
  "green bean": "Fresh Produce",
  "french bean": "Fresh Produce",
  kale: "Fresh Produce",
  kohlrabi: "Fresh Produce",
  leek: "Fresh Produce",
  lettuce: "Fresh Produce",
  mangetout: "Fresh Produce",
  marrow: "Fresh Produce",
  mushroom: "Fresh Produce",
  okra: "Fresh Produce",
  onion: "Fresh Produce",
  "pak choi": "Fresh Produce",
  parsnip: "Fresh Produce",
  pea: "Fresh Produce",
  pepper: "Fresh Produce",
  potato: "Fresh Produce",
  pumpkin: "Fresh Produce",
  radish: "Fresh Produce",
  "red onion": "Fresh Produce",
  rocket: "Fresh Produce",
  salad: "Fresh Produce",
  shallot: "Fresh Produce",
  "snap pea": "Fresh Produce",
  spinach: "Fresh Produce",
  "spring onion": "Fresh Produce",
  squash: "Fresh Produce",
  swede: "Fresh Produce",
  sweetcorn: "Fresh Produce",
  "sweet potato": "Fresh Produce",
  tomato: "Fresh Produce",
  turnip: "Fresh Produce",
  watercress: "Fresh Produce",
  zucchini: "Fresh Produce",

  // ─── Meat & Seafood ────────────────────────────────────────────────────────
  // Meat & Poultry
  bacon: "Meat & Seafood",
  beef: "Meat & Seafood",
  brisket: "Meat & Seafood",
  chicken: "Meat & Seafood",
  chorizo: "Meat & Seafood",
  duck: "Meat & Seafood",
  gammon: "Meat & Seafood",
  goose: "Meat & Seafood",
  ham: "Meat & Seafood",
  kidney: "Meat & Seafood",
  lamb: "Meat & Seafood",
  liver: "Meat & Seafood",
  mince: "Meat & Seafood",
  mutton: "Meat & Seafood",
  pancetta: "Meat & Seafood",
  "parma ham": "Meat & Seafood",
  partridge: "Meat & Seafood",
  pepperoni: "Meat & Seafood",
  pheasant: "Meat & Seafood",
  pork: "Meat & Seafood",
  prosciutto: "Meat & Seafood",
  quail: "Meat & Seafood",
  rabbit: "Meat & Seafood",
  salami: "Meat & Seafood",
  sausage: "Meat & Seafood",
  steak: "Meat & Seafood",
  turkey: "Meat & Seafood",
  veal: "Meat & Seafood",
  venison: "Meat & Seafood",
  // Fish & Seafood
  anchovy: "Meat & Seafood",
  bass: "Meat & Seafood",
  bream: "Meat & Seafood",
  calamari: "Meat & Seafood",
  clam: "Meat & Seafood",
  cod: "Meat & Seafood",
  crab: "Meat & Seafood",
  crayfish: "Meat & Seafood",
  fish: "Meat & Seafood",
  haddock: "Meat & Seafood",
  hake: "Meat & Seafood",
  halibut: "Meat & Seafood",
  herring: "Meat & Seafood",
  langoustine: "Meat & Seafood",
  lobster: "Meat & Seafood",
  mackerel: "Meat & Seafood",
  monkfish: "Meat & Seafood",
  mussel: "Meat & Seafood",
  octopus: "Meat & Seafood",
  oyster: "Meat & Seafood",
  plaice: "Meat & Seafood",
  pollock: "Meat & Seafood",
  prawn: "Meat & Seafood",
  salmon: "Meat & Seafood",
  sardine: "Meat & Seafood",
  scallop: "Meat & Seafood",
  "sea bass": "Meat & Seafood",
  seafood: "Meat & Seafood",
  shrimp: "Meat & Seafood",
  skate: "Meat & Seafood",
  sole: "Meat & Seafood",
  squid: "Meat & Seafood",
  swordfish: "Meat & Seafood",
  tilapia: "Meat & Seafood",
  trout: "Meat & Seafood",
  tuna: "Meat & Seafood",
  whitebait: "Meat & Seafood",
  whiting: "Meat & Seafood",

  // ─── Dairy & Eggs ─────────────────────────────────────────────────────────
  brie: "Dairy & Eggs",
  butter: "Dairy & Eggs",
  buttermilk: "Dairy & Eggs",
  camembert: "Dairy & Eggs",
  cheddar: "Dairy & Eggs",
  cheese: "Dairy & Eggs",
  "cottage cheese": "Dairy & Eggs",
  cream: "Dairy & Eggs",
  "cream cheese": "Dairy & Eggs",
  "creme fraiche": "Dairy & Eggs",
  "double cream": "Dairy & Eggs",
  egg: "Dairy & Eggs",
  feta: "Dairy & Eggs",
  ghee: "Dairy & Eggs",
  goat: "Dairy & Eggs",
  gouda: "Dairy & Eggs",
  gruyere: "Dairy & Eggs",
  halloumi: "Dairy & Eggs",
  manchego: "Dairy & Eggs",
  mascarpone: "Dairy & Eggs",
  milk: "Dairy & Eggs",
  mozzarella: "Dairy & Eggs",
  parmesan: "Dairy & Eggs",
  pecorino: "Dairy & Eggs",
  ricotta: "Dairy & Eggs",
  "single cream": "Dairy & Eggs",
  "sour cream": "Dairy & Eggs",
  "soured cream": "Dairy & Eggs",
  stilton: "Dairy & Eggs",
  yoghurt: "Dairy & Eggs",
  yogurt: "Dairy & Eggs",

  // ─── Bakery ───────────────────────────────────────────────────────────────
  bagel: "Bakery",
  baguette: "Bakery",
  bloomer: "Bakery",
  bread: "Bakery",
  breadcrumb: "Bakery",
  brioche: "Bakery",
  bun: "Bakery",
  ciabatta: "Bakery",
  crouton: "Bakery",
  crumpet: "Bakery",
  croissant: "Bakery",
  "english muffin": "Bakery",
  flatbread: "Bakery",
  focaccia: "Bakery",
  "hot dog bun": "Bakery",
  muffin: "Bakery",
  naan: "Bakery",
  panini: "Bakery",
  pita: "Bakery",
  pitta: "Bakery",
  roll: "Bakery",
  rye: "Bakery",
  scone: "Bakery",
  sourdough: "Bakery",
  "tiger bread": "Bakery",
  toast: "Bakery",
  tortilla: "Bakery",
  wrap: "Bakery",

  // ─── Chilled ──────────────────────────────────────────────────────────────
  coleslaw: "Chilled",
  dip: "Chilled",
  guacamole: "Chilled",
  houmous: "Chilled",
  hummus: "Chilled",
  "orange juice": "Chilled",
  pate: "Chilled",
  "puff pastry": "Chilled",
  "shortcrust pastry": "Chilled",
  pastry: "Chilled",
  "ready meal": "Chilled",
  salsa: "Chilled",
  smoothie: "Chilled",
  soup: "Chilled",
  "fresh pasta": "Chilled",
  tzatziki: "Chilled",

  // ─── Frozen ───────────────────────────────────────────────────────────────
  "frozen pea": "Frozen",
  "frozen vegetable": "Frozen",
  "frozen fruit": "Frozen",
  "frozen chip": "Frozen",
  "frozen fish": "Frozen",
  "frozen prawn": "Frozen",
  "ice cream": "Frozen",
  "frozen pizza": "Frozen",
  "frozen pastry": "Frozen",
  sorbet: "Frozen",
  gelato: "Frozen",

  // ─── Tinned & Canned ──────────────────────────────────────────────────────
  "baked bean": "Tinned & Canned",
  "black bean": "Tinned & Canned",
  "borlotti bean": "Tinned & Canned",
  "butter bean": "Tinned & Canned",
  "cannellini bean": "Tinned & Canned",
  "canned tomato": "Tinned & Canned",
  "canned tuna": "Tinned & Canned",
  chickpea: "Tinned & Canned",
  "chopped tomato": "Tinned & Canned",
  "coconut milk": "Tinned & Canned",
  "coconut cream": "Tinned & Canned",
  "haricot bean": "Tinned & Canned",
  "kidney bean": "Tinned & Canned",
  lentil: "Tinned & Canned",
  passata: "Tinned & Canned",
  "pinto bean": "Tinned & Canned",
  "tinned sweetcorn": "Tinned & Canned",
  "tinned tomato": "Tinned & Canned",
  "tinned tuna": "Tinned & Canned",
  "tomato paste": "Tinned & Canned",
  "tomato puree": "Tinned & Canned",
  "tomato passata": "Tinned & Canned",

  // ─── Pasta Rice & Grains ──────────────────────────────────────────────────
  arborio: "Pasta Rice & Grains",
  barley: "Pasta Rice & Grains",
  basmati: "Pasta Rice & Grains",
  buckwheat: "Pasta Rice & Grains",
  bulgur: "Pasta Rice & Grains",
  couscous: "Pasta Rice & Grains",
  farro: "Pasta Rice & Grains",
  freekeh: "Pasta Rice & Grains",
  fusilli: "Pasta Rice & Grains",
  gnocchi: "Pasta Rice & Grains",
  jasmine: "Pasta Rice & Grains",
  lasagne: "Pasta Rice & Grains",
  linguine: "Pasta Rice & Grains",
  macaroni: "Pasta Rice & Grains",
  noodle: "Pasta Rice & Grains",
  oat: "Pasta Rice & Grains",
  orzo: "Pasta Rice & Grains",
  pappardelle: "Pasta Rice & Grains",
  pasta: "Pasta Rice & Grains",
  penne: "Pasta Rice & Grains",
  polenta: "Pasta Rice & Grains",
  quinoa: "Pasta Rice & Grains",
  rice: "Pasta Rice & Grains",
  risotto: "Pasta Rice & Grains",
  rigatoni: "Pasta Rice & Grains",
  semolina: "Pasta Rice & Grains",
  spaghetti: "Pasta Rice & Grains",
  tagliatelle: "Pasta Rice & Grains",
  vermicelli: "Pasta Rice & Grains",
  "wild rice": "Pasta Rice & Grains",

  // ─── Herbs & Spices ───────────────────────────────────────────────────────
  allspice: "Herbs & Spices",
  anise: "Herbs & Spices",
  basil: "Herbs & Spices",
  "bay leaf": "Herbs & Spices",
  "black pepper": "Herbs & Spices",
  "bouquet garni": "Herbs & Spices",
  caraway: "Herbs & Spices",
  cardamom: "Herbs & Spices",
  cayenne: "Herbs & Spices",
  chervil: "Herbs & Spices",
  chives: "Herbs & Spices",
  cilantro: "Herbs & Spices",
  cinnamon: "Herbs & Spices",
  clove: "Herbs & Spices",
  coriander: "Herbs & Spices",
  cumin: "Herbs & Spices",
  dill: "Herbs & Spices",
  "dried herb": "Herbs & Spices",
  "fennel seed": "Herbs & Spices",
  fenugreek: "Herbs & Spices",
  "five spice": "Herbs & Spices",
  galangal: "Herbs & Spices",
  "garlic powder": "Herbs & Spices",
  herb: "Herbs & Spices",
  "italian seasoning": "Herbs & Spices",
  juniper: "Herbs & Spices",
  lavender: "Herbs & Spices",
  lemongrass: "Herbs & Spices",
  mace: "Herbs & Spices",
  marjoram: "Herbs & Spices",
  mint: "Herbs & Spices",
  "mixed herb": "Herbs & Spices",
  "mixed spice": "Herbs & Spices",
  nutmeg: "Herbs & Spices",
  "onion powder": "Herbs & Spices",
  oregano: "Herbs & Spices",
  paprika: "Herbs & Spices",
  parsley: "Herbs & Spices",
  peppercorn: "Herbs & Spices",
  rosemary: "Herbs & Spices",
  saffron: "Herbs & Spices",
  sage: "Herbs & Spices",
  salt: "Herbs & Spices",
  "sea salt": "Herbs & Spices",
  seasoning: "Herbs & Spices",
  "smoked paprika": "Herbs & Spices",
  spice: "Herbs & Spices",
  "star anise": "Herbs & Spices",
  sumac: "Herbs & Spices",
  tarragon: "Herbs & Spices",
  thyme: "Herbs & Spices",
  turmeric: "Herbs & Spices",
  "za'atar": "Herbs & Spices",
  zaatar: "Herbs & Spices",

  // ─── Condiments & Sauces ──────────────────────────────────────────────────
  aioli: "Condiments & Sauces",
  balsamic: "Condiments & Sauces",
  "bbq sauce": "Condiments & Sauces",
  "brown sauce": "Condiments & Sauces",
  capers: "Condiments & Sauces",
  chutney: "Condiments & Sauces",
  dijon: "Condiments & Sauces",
  "english mustard": "Condiments & Sauces",
  gravy: "Condiments & Sauces",
  henderson: "Condiments & Sauces",
  hollandaise: "Condiments & Sauces",
  horseradish: "Condiments & Sauces",
  "hot sauce": "Condiments & Sauces",
  "hp sauce": "Condiments & Sauces",
  jam: "Condiments & Sauces",
  ketchup: "Condiments & Sauces",
  marmalade: "Condiments & Sauces",
  mayo: "Condiments & Sauces",
  mayonnaise: "Condiments & Sauces",
  mustard: "Condiments & Sauces",
  oil: "Condiments & Sauces",
  "olive oil": "Condiments & Sauces",
  "peanut butter": "Condiments & Sauces",
  pesto: "Condiments & Sauces",
  pickle: "Condiments & Sauces",
  relish: "Condiments & Sauces",
  "salad cream": "Condiments & Sauces",
  "sunflower oil": "Condiments & Sauces",
  tabasco: "Condiments & Sauces",
  tartare: "Condiments & Sauces",
  vinegar: "Condiments & Sauces",
  "vegetable oil": "Condiments & Sauces",
  "white wine vinegar": "Condiments & Sauces",
  "red wine vinegar": "Condiments & Sauces",
  worcestershire: "Condiments & Sauces",

  // ─── World Foods ──────────────────────────────────────────────────────────
  "black bean sauce": "World Foods",
  "chilli sauce": "World Foods",
  "curry paste": "World Foods",
  "curry powder": "World Foods",
  dashi: "World Foods",
  "fish sauce": "World Foods",
  garam: "World Foods",
  gochujang: "World Foods",
  hoisin: "World Foods",
  kimchi: "World Foods",
  miso: "World Foods",
  "miso paste": "World Foods",
  nori: "World Foods",
  "oyster sauce": "World Foods",
  panko: "World Foods",
  "rice noodle": "World Foods",
  "rice paper": "World Foods",
  "rice vinegar": "World Foods",
  sambal: "World Foods",
  satay: "World Foods",
  "sesame oil": "World Foods",
  "soy sauce": "World Foods",
  sriracha: "World Foods",
  "sweet chilli": "World Foods",
  tahini: "World Foods",
  tamarind: "World Foods",
  tempeh: "World Foods",
  teriyaki: "World Foods",
  tofu: "World Foods",
  wasabi: "World Foods",
  wonton: "World Foods",

  // ─── Baking ───────────────────────────────────────────────────────────────
  almond: "Baking",
  "almond flour": "Baking",
  "baking powder": "Baking",
  "baking soda": "Baking",
  bicarbonate: "Baking",
  "brown sugar": "Baking",
  "caster sugar": "Baking",
  "chocolate chip": "Baking",
  cocoa: "Baking",
  "cocoa powder": "Baking",
  "coconut flour": "Baking",
  cornflour: "Baking",
  cornstarch: "Baking",
  "dark chocolate": "Baking",
  demerara: "Baking",
  flour: "Baking",
  "food colouring": "Baking",
  gelatine: "Baking",
  "golden syrup": "Baking",
  "ground almond": "Baking",
  honey: "Baking",
  "icing sugar": "Baking",
  lard: "Baking",
  "maple syrup": "Baking",
  marzipan: "Baking",
  "milk chocolate": "Baking",
  molasses: "Baking",
  muscovado: "Baking",
  "plain flour": "Baking",
  "self raising": "Baking",
  "self-raising": "Baking",
  shortening: "Baking",
  suet: "Baking",
  sugar: "Baking",
  syrup: "Baking",
  treacle: "Baking",
  "vanilla extract": "Baking",
  "vanilla essence": "Baking",
  "vanilla pod": "Baking",
  "white chocolate": "Baking",
  yeast: "Baking",

  // ─── Nuts & Seeds ─────────────────────────────────────────────────────────
  cashew: "Baking",
  chestnut: "Baking",
  hazelnut: "Baking",
  macadamia: "Baking",
  "mixed nut": "Baking",
  nut: "Baking",
  peanut: "Baking",
  pecan: "Baking",
  "pine nut": "Baking",
  pistachio: "Baking",
  walnut: "Baking",
  "chia seed": "Baking",
  "flax seed": "Baking",
  linseed: "Baking",
  "poppy seed": "Baking",
  "pumpkin seed": "Baking",
  seed: "Baking",
  "sesame seed": "Baking",
  "sunflower seed": "Baking",

  // ─── Dried Fruit ──────────────────────────────────────────────────────────
  "dried apricot": "Baking",
  "dried cranberry": "Baking",
  "dried fig": "Baking",
  "dried fruit": "Baking",
  prune: "Baking",
  raisin: "Baking",
  sultana: "Baking",
  currant: "Baking",

  // ─── Drinks ───────────────────────────────────────────────────────────────
  beer: "Drinks",
  brandy: "Drinks",
  cider: "Drinks",
  coffee: "Drinks",
  cola: "Drinks",
  "cranberry juice": "Drinks",
  espresso: "Drinks",
  gin: "Drinks",
  juice: "Drinks",
  lager: "Drinks",
  lemonade: "Drinks",
  liqueur: "Drinks",
  marsala: "Drinks",
  port: "Drinks",
  "red wine": "Drinks",
  rum: "Drinks",
  sherry: "Drinks",
  soda: "Drinks",
  stout: "Drinks",
  tea: "Drinks",
  tonic: "Drinks",
  vermouth: "Drinks",
  vodka: "Drinks",
  water: "Drinks",
  whiskey: "Drinks",
  whisky: "Drinks",
  "white wine": "Drinks",
  wine: "Drinks",
};

/**
 * Simple ingredient name normalization
 */
function normalizeIngredientName(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/\s+/g, " ")
    .replace(/[^\w\s'-]/g, "");
}

/**
 * Classify an ingredient into an aisle category
 * Uses the normalized ingredient name for lookup
 *
 * @param ingredientName - The ingredient name (will be normalized)
 * @returns The aisle category, defaults to "Other" if not found
 */
export function classifyIngredientAisle(ingredientName: string): Aisle {
  if (!ingredientName) return "Other";

  const lowered = normalizeIngredientName(ingredientName);

  // 1. Try exact match first
  if (INGREDIENT_TO_AISLE[lowered]) {
    return INGREDIENT_TO_AISLE[lowered];
  }

  // 2. Try matching any word in the ingredient name
  const words = lowered.split(/\s+/);
  for (const word of words) {
    if (INGREDIENT_TO_AISLE[word]) {
      return INGREDIENT_TO_AISLE[word];
    }
  }

  // 3. Try substring matching for compound ingredients
  for (const [keyword, aisle] of Object.entries(INGREDIENT_TO_AISLE)) {
    if (lowered.includes(keyword)) {
      return aisle;
    }
  }

  // 4. Default to "Other"
  return "Other";
}

/**
 * Get display order for aisles (for consistent UI ordering)
 */
export function getAisleOrder(aisle: Aisle): number {
  return AISLES.indexOf(aisle);
}
